package dashboard

const (
	ConfigHost                   = ComponentName + ".host"
	ConfigPort                   = ComponentName + ".port"
	ConfigAuthEnabled            = ComponentName + ".auth.enabled"
	ConfigAuthUser               = ComponentName + ".auth.user"
	ConfigAuthPassword           = ComponentName + ".auth.password"
	ConfigOAuth2EmailsAllowed    = ComponentName + ".oauth2.emails-allowed"
	ConfigOAuth2DomainsAllowed   = ComponentName + ".oauth2.domains-allowed"
	ConfigOAuth2BaseURL          = ComponentName + ".oauth2.base-url"
	ConfigOAuth2GithubEnabled    = ComponentName + ".oauth2.github.enabled"
	ConfigOAuth2GithubID         = ComponentName + ".oauth2.github.id"
	ConfigOAuth2GithubSecret     = ComponentName + ".oauth2.github.secret"
	ConfigOAuth2GithubScopes     = ComponentName + ".oauth2.github.scopes"
	ConfigOAuth2GitlabEnabled    = ComponentName + ".oauth2.gitlab.enabled"
	ConfigOAuth2GitlabID         = ComponentName + ".oauth2.gitlab.id"
	ConfigOAuth2GitlabSecret     = ComponentName + ".oauth2.gitlab.secret"
	ConfigOAuth2GitlabScopes     = ComponentName + ".oauth2.gitlab.scopes"
	ConfigOAuth2GitlabAuthURL    = ComponentName + ".oauth2.gitlab.auth-url"
	ConfigOAuth2GitlabTokenURL   = ComponentName + ".oauth2.gitlab.token-url"
	ConfigOAuth2GitlabProfileURL = ComponentName + ".oauth2.gitlab.profile-url"
	ConfigOAuth2GplusEnabled     = ComponentName + ".oauth2.gplus.enabled"
	ConfigOAuth2GplusID          = ComponentName + ".oauth2.gplus.id"
	ConfigOAuth2GplusSecret      = ComponentName + ".oauth2.gplus.secret"
	ConfigOAuth2GplusScopes      = ComponentName + ".oauth2.gplus.scopes"
	ConfigSessionCleanupInterval = ComponentName + ".session.cleanup-interval"
	ConfigSessionCookieName      = ComponentName + ".session.cookie-name"
	ConfigSessionDomain          = ComponentName + ".session.domain"
	ConfigSessionHTTPOnly        = ComponentName + ".session.http-only"
	ConfigSessionIdleTimeout     = ComponentName + ".session.idle-timeout"
	ConfigSessionLifetime        = ComponentName + ".session.lifetime"
	ConfigSessionPath            = ComponentName + ".session.path"
	ConfigSessionPersist         = ComponentName + ".session.persist"
	ConfigSessionSameSite        = ComponentName + ".session.same-site"
	ConfigSessionSecure          = ComponentName + ".session.secure"
	ConfigFrontendMinifyEnabled  = ComponentName + ".frontend.minify-enabled"
	ConfigStartURL               = ComponentName + ".start-url"
	ConfigPanicHandlerCallerSkip = ComponentName + ".panic-handler.caller-skip"
)
