package dashboard

const (
	ConfigHost                    = ComponentName + ".host"
	ConfigPort                    = ComponentName + ".port"
	ConfigAuthEnabled             = ComponentName + ".auth.enabled"
	ConfigAuthUser                = ComponentName + ".auth.user"
	ConfigAuthPassword            = ComponentName + ".auth.password"
	ConfigOAuth2EmailsAllowed     = ComponentName + ".oauth2.emails_allowed"
	ConfigOAuth2GithubEnabled     = ComponentName + ".oauth2.github.enabled"
	ConfigOAuth2GithubID          = ComponentName + ".oauth2.github.id"
	ConfigOAuth2GithubSecret      = ComponentName + ".oauth2.github.secret"
	ConfigOAuth2GithubScopes      = ComponentName + ".oauth2.github.scopes"
	ConfigOAuth2GithubRedirectURL = ComponentName + ".oauth2.github.redirect-url"
	ConfigOAuth2GitlabEnabled     = ComponentName + ".oauth2.gitlab.enabled"
	ConfigOAuth2GitlabID          = ComponentName + ".oauth2.gitlab.id"
	ConfigOAuth2GitlabSecret      = ComponentName + ".oauth2.gitlab.secret"
	ConfigOAuth2GitlabScopes      = ComponentName + ".oauth2.gitlab.scopes"
	ConfigOAuth2GitlabAuthURL     = ComponentName + ".oauth2.gitlab.auth-url"
	ConfigOAuth2GitlabTokenURL    = ComponentName + ".oauth2.gitlab.token-url"
	ConfigOAuth2GitlabProfileURL  = ComponentName + ".oauth2.gitlab.profile-url"
	ConfigOAuth2GitlabRedirectURL = ComponentName + ".oauth2.gitlab.redirect-url"
	ConfigSessionCookieName       = ComponentName + ".session.cookie-name"
	ConfigSessionDomain           = ComponentName + ".session.domain"
	ConfigSessionHttpOnly         = ComponentName + ".session.http-only"
	ConfigSessionIdleTimeout      = ComponentName + ".session.idle-timeout"
	ConfigSessionLifetime         = ComponentName + ".session.lifetime"
	ConfigSessionPath             = ComponentName + ".session.path"
	ConfigSessionPersist          = ComponentName + ".session.persist"
	ConfigSessionSecure           = ComponentName + ".session.secure"
	ConfigFrontendMinifyEnabled   = ComponentName + ".frontend.minify-enabled"
)
