package dashboard

const (
	ConfigHost               = ComponentName + ".host"
	ConfigPort               = ComponentName + ".port"
	ConfigAuthEnabled        = ComponentName + ".auth.enabled"
	ConfigAuthUser           = ComponentName + ".auth.user"
	ConfigAuthPassword       = ComponentName + ".auth.password"
	ConfigOAuth2Enabled      = ComponentName + ".oauth2.enabled"
	ConfigOAuth2ID           = ComponentName + ".oauth2.id"
	ConfigOAuth2Secret       = ComponentName + ".oauth2.secret"
	ConfigOAuth2Scopes       = ComponentName + ".oauth2.scopes"
	ConfigOAuth2AuthURL      = ComponentName + ".oauth2.auth-url"
	ConfigOAuth2TokenURL     = ComponentName + ".oauth2.token-url"
	ConfigOAuth2ProfileURL   = ComponentName + ".oauth2.profile-url"
	ConfigOAuth2RedirectURL  = ComponentName + ".oauth2.redirect-url"
	ConfigSessionCookieName  = ComponentName + ".session.cookie-name"
	ConfigSessionDomain      = ComponentName + ".session.domain"
	ConfigSessionHttpOnly    = ComponentName + ".session.http-only"
	ConfigSessionIdleTimeout = ComponentName + ".session.idle-timeout"
	ConfigSessionLifetime    = ComponentName + ".session.lifetime"
	ConfigSessionPath        = ComponentName + ".session.path"
	ConfigSessionPersist     = ComponentName + ".session.persist"
	ConfigSessionSecure      = ComponentName + ".session.secure"
)
