// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	VersionRequest
	VersionResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionRequest struct {
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VersionResponse struct {
	Name          string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version       string                     `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Build         string                     `protobuf:"bytes,3,opt,name=build" json:"build,omitempty"`
	BuildDatetime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=build_datetime,json=buildDatetime" json:"build_datetime,omitempty"`
	Uptime        *google_protobuf1.Duration `protobuf:"bytes,5,opt,name=uptime" json:"uptime,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionResponse) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *VersionResponse) GetBuildDatetime() *google_protobuf.Timestamp {
	if m != nil {
		return m.BuildDatetime
	}
	return nil
}

func (m *VersionResponse) GetUptime() *google_protobuf1.Duration {
	if m != nil {
		return m.Uptime
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "shadow.grpc.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "shadow.grpc.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Grpc service

type GrpcClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc1.CallOption) (*VersionResponse, error)
}

type grpcClient struct {
	cc *grpc1.ClientConn
}

func NewGrpcClient(cc *grpc1.ClientConn) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc1.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc1.Invoke(ctx, "/shadow.grpc.Grpc/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Grpc service

type GrpcServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
}

func RegisterGrpcServer(s *grpc1.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Version(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shadow.grpc.Grpc/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grpc_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "shadow.grpc.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Grpc_Version_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4b, 0x4b, 0xc3, 0x40,
	0x10, 0x36, 0x9a, 0xb6, 0x38, 0xc5, 0x2a, 0x4b, 0x91, 0x18, 0x45, 0x4b, 0x4e, 0x3d, 0x6d, 0xb0,
	0xfe, 0x02, 0xa5, 0xe8, 0xcd, 0x43, 0x10, 0x0f, 0x5e, 0x24, 0x8f, 0x35, 0x06, 0x9a, 0x9d, 0x75,
	0x1f, 0xfa, 0x23, 0xfd, 0x53, 0x92, 0xd9, 0x44, 0x7c, 0xf4, 0x32, 0xcc, 0x7c, 0x0f, 0xf8, 0xbe,
	0x01, 0xa8, 0xb5, 0x2a, 0xb9, 0xd2, 0x68, 0x91, 0x4d, 0xcd, 0x6b, 0x5e, 0xe1, 0x07, 0xef, 0xa0,
	0xf8, 0xa2, 0x46, 0xac, 0x37, 0x22, 0x25, 0xaa, 0x70, 0x2f, 0xa9, 0x6d, 0x5a, 0x61, 0x6c, 0xde,
	0x2a, 0xaf, 0x8e, 0xcf, 0xff, 0x0a, 0x2a, 0xa7, 0x73, 0xdb, 0xa0, 0xf4, 0x7c, 0x72, 0x04, 0xb3,
	0x47, 0xa1, 0x4d, 0x83, 0x32, 0x13, 0x6f, 0x4e, 0x18, 0x9b, 0x7c, 0x06, 0x70, 0xf8, 0x0d, 0x19,
	0x85, 0xd2, 0x08, 0xc6, 0x20, 0x94, 0x79, 0x2b, 0xa2, 0x60, 0x11, 0x2c, 0xf7, 0x33, 0xda, 0x59,
	0x04, 0x93, 0x77, 0x2f, 0x8b, 0x76, 0x09, 0x1e, 0x4e, 0x36, 0x87, 0x51, 0xe1, 0x9a, 0x4d, 0x15,
	0xed, 0x11, 0xee, 0x0f, 0x76, 0x0d, 0x33, 0x5a, 0x9e, 0xab, 0xdc, 0x8a, 0x2e, 0x66, 0x14, 0x2e,
	0x82, 0xe5, 0x74, 0x15, 0x73, 0x1f, 0x91, 0x0f, 0x11, 0xf9, 0xc3, 0xd0, 0x21, 0x3b, 0x20, 0xc7,
	0xba, 0x37, 0xb0, 0x4b, 0x18, 0x3b, 0x45, 0xd6, 0x11, 0x59, 0x4f, 0xfe, 0x59, 0xd7, 0x7d, 0xbb,
	0xac, 0x17, 0xae, 0xee, 0x21, 0xbc, 0xd3, 0xaa, 0x64, 0xb7, 0x30, 0xe9, 0x4b, 0xb1, 0x53, 0xfe,
	0xe3, 0x83, 0xfc, 0x77, 0xfb, 0xf8, 0x6c, 0x3b, 0xe9, 0xff, 0x90, 0xec, 0xdc, 0x1c, 0x3f, 0xcd,
	0x4b, 0x6c, 0x15, 0x4a, 0x21, 0xad, 0x49, 0x3b, 0x11, 0x8d, 0x62, 0x4c, 0x11, 0xae, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x9e, 0xae, 0x14, 0x06, 0xaa, 0x01, 0x00, 0x00,
}
