// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package workers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers(in *jlexer.Lexer, out *ajaxHandlerResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tasks_wait":
			if in.IsNull() {
				in.Skip()
				out.Tasks = nil
			} else {
				in.Delim('[')
				if out.Tasks == nil {
					if !in.IsDelim(']') {
						out.Tasks = make([]ajaxHandlerResponseTask, 0, 1)
					} else {
						out.Tasks = []ajaxHandlerResponseTask{}
					}
				} else {
					out.Tasks = (out.Tasks)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ajaxHandlerResponseTask
					(v1).UnmarshalEasyJSON(in)
					out.Tasks = append(out.Tasks, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "workers":
			if in.IsNull() {
				in.Skip()
				out.Workers = nil
			} else {
				in.Delim('[')
				if out.Workers == nil {
					if !in.IsDelim(']') {
						out.Workers = make([]ajaxHandlerResponseWorker, 0, 1)
					} else {
						out.Workers = []ajaxHandlerResponseWorker{}
					}
				} else {
					out.Workers = (out.Workers)[:0]
				}
				for !in.IsDelim(']') {
					var v2 ajaxHandlerResponseWorker
					(v2).UnmarshalEasyJSON(in)
					out.Workers = append(out.Workers, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "workers_count":
			out.WorkersCount = int(in.Int())
		case "workers_wait":
			out.WorkersWait = int(in.Int())
		case "workers_busy":
			out.WorkersBusy = int(in.Int())
		case "listeners":
			if in.IsNull() {
				in.Skip()
				out.Listeners = nil
			} else {
				in.Delim('[')
				if out.Listeners == nil {
					if !in.IsDelim(']') {
						out.Listeners = make([]ajaxHandlerResponseListener, 0, 1)
					} else {
						out.Listeners = []ajaxHandlerResponseListener{}
					}
				} else {
					out.Listeners = (out.Listeners)[:0]
				}
				for !in.IsDelim(']') {
					var v3 ajaxHandlerResponseListener
					(v3).UnmarshalEasyJSON(in)
					out.Listeners = append(out.Listeners, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "listeners_count":
			out.ListenersCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers(out *jwriter.Writer, in ajaxHandlerResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"tasks_wait\":")
	if in.Tasks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v4, v5 := range in.Tasks {
			if v4 > 0 {
				out.RawByte(',')
			}
			(v5).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"workers\":")
	if in.Workers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v6, v7 := range in.Workers {
			if v6 > 0 {
				out.RawByte(',')
			}
			(v7).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"workers_count\":")
	out.Int(int(in.WorkersCount))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"workers_wait\":")
	out.Int(int(in.WorkersWait))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"workers_busy\":")
	out.Int(int(in.WorkersBusy))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"listeners\":")
	if in.Listeners == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in.Listeners {
			if v8 > 0 {
				out.RawByte(',')
			}
			(v9).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"listeners_count\":")
	out.Int(int(in.ListenersCount))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ajaxHandlerResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ajaxHandlerResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ajaxHandlerResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ajaxHandlerResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers(l, v)
}
func easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers1(in *jlexer.Lexer, out *ajaxHandlerResponseListener) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "last_task_success_at":
			if in.IsNull() {
				in.Skip()
				out.LastTaskSuccessAt = nil
			} else {
				if out.LastTaskSuccessAt == nil {
					out.LastTaskSuccessAt = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.LastTaskSuccessAt).UnmarshalJSON(data))
				}
			}
		case "last_task_failed_at":
			if in.IsNull() {
				in.Skip()
				out.LastTaskFailedAt = nil
			} else {
				if out.LastTaskFailedAt == nil {
					out.LastTaskFailedAt = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.LastTaskFailedAt).UnmarshalJSON(data))
				}
			}
		case "count_task_success":
			out.CountTaskSuccess = uint64(in.Uint64())
		case "count_task_failed":
			out.CountTaskFailed = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers1(out *jwriter.Writer, in ajaxHandlerResponseListener) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"created_at\":")
	out.Raw((in.CreatedAt).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"last_task_success_at\":")
	if in.LastTaskSuccessAt == nil {
		out.RawString("null")
	} else {
		out.Raw((*in.LastTaskSuccessAt).MarshalJSON())
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"last_task_failed_at\":")
	if in.LastTaskFailedAt == nil {
		out.RawString("null")
	} else {
		out.Raw((*in.LastTaskFailedAt).MarshalJSON())
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"count_task_success\":")
	out.Uint64(uint64(in.CountTaskSuccess))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"count_task_failed\":")
	out.Uint64(uint64(in.CountTaskFailed))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ajaxHandlerResponseListener) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ajaxHandlerResponseListener) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ajaxHandlerResponseListener) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ajaxHandlerResponseListener) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers1(l, v)
}
func easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers2(in *jlexer.Lexer, out *ajaxHandlerResponseWorker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "created":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Created).UnmarshalJSON(data))
			}
		case "status":
			out.Status = int64(in.Int64())
		case "task":
			if in.IsNull() {
				in.Skip()
				out.Task = nil
			} else {
				if out.Task == nil {
					out.Task = new(ajaxHandlerResponseTask)
				}
				(*out.Task).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers2(out *jwriter.Writer, in ajaxHandlerResponseWorker) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"created\":")
	out.Raw((in.Created).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"status\":")
	out.Int64(int64(in.Status))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"task\":")
	if in.Task == nil {
		out.RawString("null")
	} else {
		(*in.Task).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ajaxHandlerResponseWorker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ajaxHandlerResponseWorker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ajaxHandlerResponseWorker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ajaxHandlerResponseWorker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers2(l, v)
}
func easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers3(in *jlexer.Lexer, out *ajaxHandlerResponseTask) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "status":
			out.Status = int64(in.Int64())
		case "priority":
			out.Priority = int64(in.Int64())
		case "attempts":
			out.Attempts = int64(in.Int64())
		case "last_error":
			if m, ok := out.LastError.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.LastError.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.LastError = in.Interface()
			}
		case "created":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Created).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers3(out *jwriter.Writer, in ajaxHandlerResponseTask) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"status\":")
	out.Int64(int64(in.Status))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"priority\":")
	out.Int64(int64(in.Priority))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"attempts\":")
	out.Int64(int64(in.Attempts))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"last_error\":")
	if m, ok := in.LastError.(easyjson.Marshaler); ok {
		m.MarshalEasyJSON(out)
	} else if m, ok := in.LastError.(json.Marshaler); ok {
		out.Raw(m.MarshalJSON())
	} else {
		out.Raw(json.Marshal(in.LastError))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"created\":")
	out.Raw((in.Created).MarshalJSON())
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ajaxHandlerResponseTask) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ajaxHandlerResponseTask) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ajaxHandlerResponseTask) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ajaxHandlerResponseTask) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers3(l, v)
}
func easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers4(in *jlexer.Lexer, out *ajaxHandlerResponseSuccess) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers4(out *jwriter.Writer, in ajaxHandlerResponseSuccess) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"result\":")
	out.String(string(in.Result))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ajaxHandlerResponseSuccess) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ajaxHandlerResponseSuccess) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDce94ab1EncodeGithubComKihamoShadowComponentsWorkers4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ajaxHandlerResponseSuccess) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ajaxHandlerResponseSuccess) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDce94ab1DecodeGithubComKihamoShadowComponentsWorkers4(l, v)
}
